package euler;

/**
 * Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, 
 * the first 10 terms will be:

1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

By considering the terms in the Fibonacci sequence whose values do not exceed four million, 
find the sum of the even-valued terms.

 * @author premkumarnarayanappavenkatesh
 *
 */
public class EvenFib {
	
	private static int FOUR_MILLION = 4000000;
	
	private static int fib(int val1,int val2, int sum){
		if(val2 > FOUR_MILLION){
			return sum;
		}
		if(val2 %2 ==0){
			sum = sum+val2;
		}
			
		return fib(val2, val1 +val2, sum);
	}

	public static void main(String[] args) {
		System.out.println(fib(1, 2, 0));
	}
}
